sudo: false
language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test --cov=httprunner --cov-report term-missing
after_success:
  - coveralls